import {
  Microscope, FlaskConical, FlaskRound, TestTube, TestTubes, Atom, Dna, Brain, BrainCircuit, Telescope, Orbit, Magnet,
  Pen, Pencil, PenTool, Notebook, NotebookPen, BookOpen, BookMarked, BookText, Quote, Highlighter, TextCursorInput, SpellCheck,
  Database, DatabaseBackup, Table, TableProperties, ChartBar, ChartLine, ChartPie, ChartScatter, ChartArea, ChartColumn, Funnel, Rows3,
  Code, CodeXml, Terminal, Braces, Brackets, Binary, Bug, GitBranch, GitMerge, GitPullRequest, Cpu, Webhook,
  MessageCircle, MessageSquare, MessagesSquare, Mail, MailOpen, Send, Phone, Video, Mic, Megaphone, Languages, Speech,
  Calendar, CalendarDays, CalendarCheck, Clock, Timer, AlarmClock, ListTodo, ListChecks, Target, Flag, Milestone, Kanban,
  File, FileText, FileCheck, FileSearch, FileCode, FileImage, Files, Folder, FolderOpen, FolderCheck, Archive, Clipboard,
  Check, CheckCheck, CircleCheck, Shield, ShieldCheck, ShieldAlert, BadgeCheck, Scan, ScanLine, SearchCheck, Scale, Fingerprint,
  Calculator, Sigma, Pi, Percent, Divide, Plus, Minus, Equal, Radical, Ruler, Triangle, Compass,
  Wrench, Hammer, Settings, SlidersHorizontal, Workflow, Network, Layers, Lightbulb, WandSparkles, Sparkles, Rocket, Puzzle,
  User, Users, UserCheck, Contact, Handshake, Presentation, GraduationCap, Briefcase, Building, Landmark, Globe, Map,
  Image, Images, Camera, Film, Clapperboard, Music, Headphones, Palette, Paintbrush, Shapes, Box, Monitor,
  type LucideIcon,
} from 'lucide-react';
import type { SkillIconId } from '../../lib/skillAppearance';

export const skillIconRegistry = {
  microscope: Microscope, 'flask-conical': FlaskConical, 'flask-round': FlaskRound, 'test-tube': TestTube, 'test-tubes': TestTubes,
  atom: Atom, dna: Dna, brain: Brain, 'brain-circuit': BrainCircuit, telescope: Telescope, orbit: Orbit, magnet: Magnet,
  pen: Pen, pencil: Pencil, 'pen-tool': PenTool, notebook: Notebook, 'notebook-pen': NotebookPen, 'book-open': BookOpen,
  'book-marked': BookMarked, 'book-text': BookText, quote: Quote, highlighter: Highlighter, 'text-cursor-input': TextCursorInput, 'spell-check': SpellCheck,
  database: Database, 'database-backup': DatabaseBackup, table: Table, 'table-properties': TableProperties,
  'chart-bar': ChartBar, 'chart-line': ChartLine, 'chart-pie': ChartPie, 'chart-scatter': ChartScatter, 'chart-area': ChartArea,
  'chart-column': ChartColumn, funnel: Funnel, 'rows-3': Rows3,
  code: Code, 'code-xml': CodeXml, terminal: Terminal, braces: Braces, brackets: Brackets, binary: Binary, bug: Bug,
  'git-branch': GitBranch, 'git-merge': GitMerge, 'git-pull-request': GitPullRequest, cpu: Cpu, webhook: Webhook,
  'message-circle': MessageCircle, 'message-square': MessageSquare, 'messages-square': MessagesSquare,
  mail: Mail, 'mail-open': MailOpen, send: Send, phone: Phone, video: Video, mic: Mic, megaphone: Megaphone, languages: Languages, speech: Speech,
  calendar: Calendar, 'calendar-days': CalendarDays, 'calendar-check': CalendarCheck, clock: Clock, timer: Timer,
  'alarm-clock': AlarmClock, 'list-todo': ListTodo, 'list-checks': ListChecks, target: Target, flag: Flag, milestone: Milestone, kanban: Kanban,
  file: File, 'file-text': FileText, 'file-check': FileCheck, 'file-search': FileSearch, 'file-code': FileCode, 'file-image': FileImage,
  files: Files, folder: Folder, 'folder-open': FolderOpen, 'folder-check': FolderCheck, archive: Archive, clipboard: Clipboard,
  check: Check, 'check-check': CheckCheck, 'circle-check': CircleCheck, shield: Shield, 'shield-check': ShieldCheck, 'shield-alert': ShieldAlert,
  'badge-check': BadgeCheck, scan: Scan, 'scan-line': ScanLine, 'search-check': SearchCheck, scale: Scale, fingerprint: Fingerprint,
  calculator: Calculator, sigma: Sigma, pi: Pi, percent: Percent, divide: Divide, plus: Plus, minus: Minus, equal: Equal,
  radical: Radical, ruler: Ruler, triangle: Triangle, compass: Compass,
  wrench: Wrench, hammer: Hammer, settings: Settings, 'sliders-horizontal': SlidersHorizontal, workflow: Workflow, network: Network,
  layers: Layers, lightbulb: Lightbulb, 'wand-sparkles': WandSparkles, sparkles: Sparkles, rocket: Rocket, puzzle: Puzzle,
  user: User, users: Users, 'user-check': UserCheck, contact: Contact, handshake: Handshake, presentation: Presentation,
  'graduation-cap': GraduationCap, briefcase: Briefcase, building: Building, landmark: Landmark, globe: Globe, map: Map,
  image: Image, images: Images, camera: Camera, film: Film, clapperboard: Clapperboard, music: Music,
  headphones: Headphones, palette: Palette, paintbrush: Paintbrush, shapes: Shapes, box: Box, monitor: Monitor,
} satisfies Record<SkillIconId, LucideIcon>;