import type { AnswerDebugInfo } from '../../lib/answerDebug';
import type { AgentOutputVersion } from '../../lib/agentOutputHistory';
import type { StepRunDiagnostics } from '../../lib/stepExecution';
import type { SkillRef } from '../../lib/projectSkills';
import type { AgentCorpusRef } from '../../lib/agentFiles';

export interface Canvas272Layer {
  id: string;
  name: string;
  userInstruction?: string;
  systemInstruction?: string;
  result?: string;
  outputHistory?: AgentOutputVersion[];
  output?: string;
  assistantResponse?: string;
  /**
   * Data URLs (`data:image/...;base64,...`) of images generated by an image
   * model on this step. Kept separate from result/output/assistantResponse on
   * purpose: those fields are concatenated into downstream step prompts, so
   * base64 there would bloat prompts. result may hold only the text caption.
   */
  imageUrls?: string[];
  referencedSteps?: string[];
  tag?: string;
  order?: number;
  isActive?: boolean;
  selectedModel?: string;
  maxTokens?: number;
  temperature?: number;
  debugInfo?: AnswerDebugInfo;
  lastRunDiagnostics?: StepRunDiagnostics;
  /** Durable file-search corpus attached to this step (used by single-step + Run All). */
  corpusId?: string;
  /** Human-readable corpus name captured at attach time; survives cross-user sharing where the viewer's registry can't resolve the id. */
  corpusDisplayName?: string;
  /** Email of the user who attached this corpus to the step (creator tracking for shared projects). */
  corpusOwnerEmail?: string;
  /** In-flight ingestion job for files uploaded on this step; lets the editor resume polling. */
  uploadFileJobId?: string;
  /** Display names of files ingested into this step's corpus. */
  uploadedFileNames?: string[];
  [key: string]: unknown;
}

export interface Canvas272Agent {
  id: string;
  name: string;
  layers: Canvas272Layer[];
  currentVersion?: string;
  versions?: string[];
  metadata?: {
    created?: string;
    modified?: string;
    description?: string;
    displayTitle?: string;
    skillIds?: string[];
    skillRefs?: SkillRef[];
    fileIds?: string[];
    corpusRefs?: AgentCorpusRef[];
  };
}

export interface Canvas272SidecarV1 {
  version: 1;
  agentId: string;
  agentName: string;
  updatedAt: string;
  outputs: Record<string, string>;
}

export interface DiagramSection {
  id: string;
  label: string;
  mainLaneIndex: number;
  headerLayer: Canvas272Layer;
  children: Canvas272Layer[];
}

export interface DiagramModel {
  mainLane: Array<
    | { kind: 'step'; layer: Canvas272Layer; globalIndex: number }
    | { kind: 'section'; section: DiagramSection; globalIndex: number }
  >;
  sections: DiagramSection[];
}
